# Generated by Django 4.1 on 2022-12-29 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('delete', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('delete', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deplist', to='cliente.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('avenida', models.CharField(max_length=250)),
                ('barrioColonia', models.CharField(max_length=250)),
                ('zonaComunidad', models.CharField(max_length=250)),
                ('numeroCasa', models.IntegerField()),
                ('referencia', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('delete', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentolist', to='cliente.departamento')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipiolist', to='cliente.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=9)),
                ('telefonoOne', models.CharField(max_length=12)),
                ('telefonoTwo', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion', to='cliente.direccion')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoclientelist', to='cliente.tipocliente')),
            ],
        ),
    ]
