# Generated by Django 4.1 on 2022-12-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipocliente',
            unique_together={('nombre',)},
        ),
    ]
