# Generated by Django 4.1 on 2022-12-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_tipocliente_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipocliente',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='delete',
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccioncliente', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clientelist', to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='tipocliente',
            unique_together={('cliente',)},
        ),
        migrations.RemoveField(
            model_name='tipocliente',
            name='delete',
        ),
    ]
