# Generated by Django 4.1 on 2022-12-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_tipocliente_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipocliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clientelist', to='cliente.tipocliente'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('tipo_cliente', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='tipocliente',
            name='cliente',
        ),
    ]
